name: Build and deploy tutor
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Import Workflow
        run: |
          git clone https://github.com/Abstract-Tech/community-theme-tutor.git
      
      - uses: ./community-theme-tutor/.github/workflows/tutor.yml