name: Build and deploy tutor
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to community-tutor repo
        uses: actions/checkout@master
        with:
          repository: Abstract-Tech/community-theme-tutor
          path: community-theme-tutor
      
      - uses: ./community-theme-tutor/.github/workflows/tutor.yml