name: Build and deploy tutor
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import Workflow
        uses: "docker://alpine/git"
        with:
          args: ["clone", "--depth", "1", "https://github.com/Abstract-Tech/community-theme-tutor.git", "./community-theme-tutor"]
      - uses: ./community-theme-tutor/.github/workflows/tutor.yml